### ISSUE TITLE
 Issue with Loading Weights for PARSeq Model During Inference

### ISSUE THREAD

**Issue by 258863** [mkoshkina/jersey-number-pipeline#3]
。

**Comment by Friman04** [comment]
same.

python str.py parseq_finetune.ckpt

Additional keyword arguments: {'charset_test': '0123456789'}
Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\parseq_finetune.ckpt`
Traceback (most recent call last):
  File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 320, in <module>
    main()
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 264, in main
    model = load_from_checkpoint(args.checkpoint, **kwargs).eval().to(args.device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BaiduSyncdisk\myArchives\university\competition\足球解说智能体\id\jersey-number-pipeline-main\strhub\models\utils.py", line 92, in load_from_checkpoint
    model = ModelClass.load_from_checkpoint(checkpoint_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 187, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Friman\.conda\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PARSeq:
        Missing key(s) in state_dict: "model.pos_queries", "model.encoder.pos_embed", "model.encoder.patch_embed.proj.weight", "model.encoder.patch_embed.proj.bias", "model.encoder.blocks.0.norm1.weight", "model.encoder.blocks.0.norm1.bias", "model.encoder.blocks.0.attn.qkv.weight", "model.encoder.blocks.0.attn.qkv.bias", "model.encoder.blocks.0.attn.proj.weight", "model.encoder.blocks.0.attn.proj.bias",.....................

**Comment by Past-Tang** [comment]
Has this problem been solved now

> same.
> 
> python str.py parseq_finetune.ckpt
> 
> Additional keyword arguments: {'charset_test': '0123456789'} Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\parseq_finetune.ckpt` Traceback (most recent call last): File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 320, in main() File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 264, in main model = load_from_checkpoint(args.checkpoint, **kwargs).eval().to(args.device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BaiduSyncdisk\myArchives\university\competition\足球解说智能体\id\jersey-number-pipeline-main\strhub\models\utils.py", line 92, in load_from_checkpoint model = ModelClass.load_from_checkpoint(checkpoint_path, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 125, in wrapper return self.method(cls, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\module.py", line 1582, in load_from_checkpoint loaded = _load_from_checkpoint( ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 91, in _load_from_checkpoint model = _load_state(cls, checkpoint, strict=strict, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 187, in _load_state keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for PARSeq: Missing key(s) in state_dict: "model.pos_queries", "model.encoder.pos_embed", "model.encoder.patch_embed.proj.weight", "model.encoder.patch_embed.proj.bias", "model.encoder.blocks.0.norm1.weight", "model.encoder.blocks.0.norm1.bias", "model.encoder.blocks.0.attn.qkv.weight", "model.encoder.blocks.0.attn.qkv.bias", "model.encoder.blocks.0.attn.proj.weight", "model.encoder.blocks.0.attn.proj.bias",.....................

Has this problem been solved now

**Comment by Friman04** [comment]
> Has this problem been solved now
> 
> > same.
> > python str.py parseq_finetune.ckpt
> > Additional keyword arguments: {'charset_test': '0123456789'} Lightning automatically upgraded your loaded checkpoint from v1.9.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\parseq_finetune.ckpt` Traceback (most recent call last): File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 320, in main() File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "D:\BaiduSyncdisk\myArchives\university\competition\soccer\id\jersey-number-pipeline-main\str.py", line 264, in main model = load_from_checkpoint(args.checkpoint, **kwargs).eval().to(args.device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\BaiduSyncdisk\myArchives\university\competition\足球解说智能体\id\jersey-number-pipeline-main\strhub\models\utils.py", line 92, in load_from_checkpoint model = ModelClass.load_from_checkpoint(checkpoint_path, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 125, in wrapper return self.method(cls, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\module.py", line 1582, in load_from_checkpoint loaded = _load_from_checkpoint( ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 91, in _load_from_checkpoint model = _load_state(cls, checkpoint, strict=strict, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\pytorch_lightning\core\saving.py", line 187, in _load_state keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Friman.conda\envs\yolo\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for PARSeq: Missing key(s) in state_dict: "model.pos_queries", "model.encoder.pos_embed", "model.encoder.patch_embed.proj.weight", "model.encoder.patch_embed.proj.bias", "model.encoder.blocks.0.norm1.weight", "model.encoder.blocks.0.norm1.bias", "model.encoder.blocks.0.attn.qkv.weight", "model.encoder.blocks.0.attn.qkv.bias", "model.encoder.blocks.0.attn.proj.weight", "model.encoder.blocks.0.attn.proj.bias",.....................
> 
> Has this problem been solved now

没有捏，我先卷agents去了

**Comment by mkoshkina** [comment]
Sorry for the delay. The original Parseq code has changed and is now different from the version used to develop the jersey number pipeline. I am looking into committing the version used in our code.

**Comment by mkoshkina** [comment]
I've committed the version of PARSeq code that was used to train jersey number model.  Give it a try and let me know if there are still issues loading model weights.
